### ISSUE TITLE
I request ownership of this organization.

### ISSUE THREAD

**Issue by saku-bruh** [ExynOS-ROM/packages_apps_Settings#2]
give me ownership **_NOW_**
![image](https://user-images.githubusercontent.com/67262050/230725532-3ca0dd21-a6ba-40a1-b029-8ead594f78d0.png)

**Comment by JeyKul** [comment]
lmao me too 

![image](https://user-images.githubusercontent.com/77121325/230725723-08f148ec-4a70-407c-9d4b-57360eaadc87.png)

**Comment by arthefaz** [comment]
i am owner
